spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/management_customer
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true