spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seu_banco_de_dados
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect