cors:
  originPatterns: http://localhost:8080,https://erudio.com.br
security:
  jwt:
    secret-key: 53cr37
    expire-length: 3600000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_spring_boot
    username: root
    password: # Adicione sua senha aqui
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true
